### ISSUE TITLE
ember-cli build fails when enabling sourcemap

### ISSUE THREAD

**Issue by kamal** [ef4/broccoli-uglify-sourcemap#1]
Here are the steps to reproduce:

(Using ember-cli 0.2.0)

```
$ ember new foo
  ... output ...
$ cd foo
```

Edit `Brocfile.js`

```javascript
var app = new EmberApp({
  sourcemaps: ['js']
});
```

Build it

```
$ ember build --env production
``` 

The output of the last step

```
Kamals-MacBook-Pro:baz kamal$ ember build --env production
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/kamal/src/baz/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
version: 0.2.0
BuildingThe package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/kamal/src/baz/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Build failed.
Invalid mapping: {"generated":{"line":74919,"column":-50},"source":"vendor/ember-cli/vendor-suffix.js","original":{"line":1,"column":0},"name":null}
Error: Invalid mapping: {"generated":{"line":74919,"column":-50},"source":"vendor/ember-cli/vendor-suffix.js","original":{"line":1,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:272:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:102:12)
    at /Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:74:19
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-consumer.js:473:10)
    at Function.SourceMapGenerator_fromSourceMap (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:50:26)
    at Object.SourceMap (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/sourcemap.js:59:52)
    at Object.exports.minify (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:112:38)
    at UglifyWriter.processFile (/Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:98:25)
    at /Users/kamal/src/baz/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:46:14
```

**Comment by ef4** [comment]
I think this is the same issue as https://github.com/ember-cli/ember-cli-uglify/issues/4.

**Comment by ef4** [comment]
(But thank you for the bug report -- your example is the easiest to reproduce!)

**Comment by ef4** [comment]
Closing in favor of https://github.com/emberjs/data/issues/2871
