### ISSUE TITLE
UglifyJS 2.6.0 breaks broccoli-uglify-sourcemap

### ISSUE THREAD

**Issue by dlo83** [ef4/broccoli-uglify-sourcemap#17]
After this sub-dependency was updated to 2.6 yesterday, our app no longer builds in our production environment.  Downgrading back down to UglifyJS 2.5.0 will resolve the issue.  Not sure if there is a breaking change in that project that needs to be accommodated.

Error/stack trace:

Error received
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>)
    at eval (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:3011:29)
    at Object.merge.before (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:5142:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2894:35)
    at eval (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:3012:29)
    at Object.merge.before (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:5142:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2894:35)
    at eval (eval at <anonymous> (/Users<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:3012:29)
    at Object.merge.before (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:5142:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/<redacted>/Dev/<redacted>/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2894:35)

**Comment by stefanpenner** [comment]
@dlo83 sounds like a breaking change on there side, we may want to lock our version down ...

My guess is uglification of a somewhat large file?

**Comment by dlo83** [comment]
Correctamundo.

**Comment by stefanpenner** [comment]
@dlo83 can you share the size, im curious if there is a specific cliff. Although i suspect it is depth complexity not overall size.

**Comment by dlo83** [comment]
@stefanpenner I already downgraded to 2.5, so give me a few to try and recreate again and give you more specifics.  In the meantime, could I tag you in to the discussion at https://github.com/mishoo/UglifyJS2/issues/863 ? The uglifyJS dev wants more information as to how this plugin calls uglify, and being fairly new to Ember, I'm not sure I'm the best resource on the subject.

**Comment by dlo83** [comment]
@stefanpenner, I'm not sure how to get more verbose metrics/logs around the error; I pasted it directly from the terminal into the GitHub ticket.  If you could shed some more light on how I can grab more in-depth information for you, I'd be happy to help.

**Comment by dlo83** [comment]
@stefanpenner, does this plugin allow for compress options to be configured? I can avoid the uglify errors if I set "sequences" to false.

**Comment by stefanpenner** [comment]
yes options are passed straight through:

* https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/index.js#L22-L26
* https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/index.js#L118

**Comment by dlo83** [comment]
Sure, I'll try it out for myself to verify and then create a PR.

**Comment by dlo83** [comment]
@stefanpenner, sorry if this is a noob question, but I'm trying to figure out where I would override these options within the context of our Brocfile.  (We're using an older version of Ember, so no .ember-cli)

Where in the following snippet would I pass through those compressor options ultimately consumed by uglify-js?

```
var app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true,
      extensions: ['js']
    },
    minifyCSS: { enabled: true },
    minifyJS:  { enabled: true },
```

**Comment by blimmer** [comment]
I'm suddenly experiencing this same problem. Trying to investigate, but it seems like we might want to peg the version and do a release in the meantime so people aren't stuck.

**Comment by stefanpenner** [comment]
> but it seems like we might want to peg the version and do a release in the meantime so people aren't stuck.

yes, i am tempted. Would except a PR doing this as an interim step.

**Comment by blimmer** [comment]
Confirming that locking to `~2.5.0` works on my project, then a PR is on the way.

**Comment by blimmer** [comment]
Confirm that the PR (#18) resolves the issue on my project.

**Comment by blimmer** [comment]
This isn't a long-term solution, but I determined that this issue occurred only when I was building for my staging environment, not my production environment.

In looking at the produced code, I realized that **all** of my tests were being included in the app.js file that was being passed to uglifyjs. By telling ember-cli to not include tests in my staging build, I have this working against 1.0.1.

I turned off tests by including this statement in my Brocfile.js (or ember-cli-build.js).

```javascript
var isProductionLikeBuild = ['production', 'staging'].indexOf(env) > -1;

var app = new EmberApp({
  tests:             !isProductionLikeBuild,
  ...
});
```

Not a great long-term solution, but this might help those in a pinch.

**Comment by stefanpenner** [comment]
Cli has no concept of staging. Production plus env vars to configure the build is prescribed

**Comment by blimmer** [comment]
Yep, I have to re-implement some behavior in my build file for the staging environment. I turn back on minification of JS and CSS, embed certain inline content (e.g. external scripts), etc.

However, I didn't think/realize my tests were being included and that turned out to be the addition that was pushing uglify js over the edge for me. I could see others with similar apps to mine (with lots of tests) potentially running into this issue in their staging environments (as they're pretty darn common) before the new release is out #20 . Additionally, people might have to `nombom` unless a new version of ember-cli-uglify is released with a dependency bump for this project.

**Comment by stefanpenner** [comment]
tmp fix, hopefully uglify fixes 4reals soon.

```
➜  broccoli-uglify-sourcemap git:(master) npm publish
+ broccoli-uglify-sourcemap@1.1.0
```
